name: CI/CD

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

      runs-on: ubuntu-latest

      steps:
        - uses: action/checkout@v3
        - name: use nodejs 19.8
          with:
            node-version: 19.x
          - run: npm ci
          -run: npm run build --if-present
  
  deploy:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api: ${{secrets.heroku_api_key}}
          heroku_app_name: shoppapp
          heroku_email: "seunolanitori@gmail.com",
          appdir: "dist"
        env:
          HD_MONGODB_URL: ${{secrets.MONGODB_URL}}
          HD_JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
          HD_STRIPE_KEY: ${{secrets.STRIPE_KEY}}
